#!/bin/bash

function is_initial_commit() {
    if git rev-parse HEAD^ >/dev/null 2>&1; then
        return 1
    fi
    return 0
}
function has_blogging_branch() {
    blogging_branch=`git config --get devblog.blogging-branch`
    if git rev-parse "$blogging_branch" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}
function start_blogging_branch() {
    git checkout --orphan `git config --get devblog.blogging-branch`
    git rm -rf .
}
function get_commit_info() {
  git show -s --format="$1" "$2"
}
function get_commit_body() {
  tmp=`mktemp XXXXXXXXXXXXXX`
  git show -s --format="%b" "$1" > "$tmp"
  if [ "`cat \"$tmp\" | sed \"/^$/d\" | wc -l`" != "0" ]; then
    echo "$tmp"
  else
    rm "$tmp"
  fi
}
function sanit_mail() {
  sed "s/@/[at]/;s/\./(dot)/"
}
function apply_shell_expansion() {
    declare data="$1"
    declare delimiter="__apply_shell_expansion_delimiter__"
    declare command="cat <<$delimiter"$'\n'"$data"$'\n'"$delimiter"
    eval "$command"
}

if [ -f .git/devblog.lock ]; then
    exit 0
fi

touch .git/devblog.lock

original_head=`git rev-parse HEAD`
original_branch=`git rev-parse --abbrev-ref HEAD`
if is_initial_commit; then
    start_blogging_branch
else
    if ! has_blogging_branch; then
        start_blogging_branch
    else
        git checkout `git config --get devblog.blogging-branch`
    fi
fi

commit_Hash=`get_commit_info "%H" "$original_head"`
commit_hash=`get_commit_info "%h" "$original_head"`
commit_author=`get_commit_info "%an" "$original_head"`
commit_author_email=`get_commit_info "%ae" "$original_head" | sanit_mail`
commit_datetime=`get_commit_info "%ai" "$original_head"`
commit_datetime_html5=`echo "$commit_datetime" | sed "s/ /T/;s/ \(+\|-\)\([0-9][0-9]\)/\1\2:/"`
commit_date=`echo $commit_datetime | cut -d' ' -f1`
commit_time=`echo $commit_datetime | cut -d' ' -f2`
commit_timestamp=`get_commit_info "%at" "$original_head"`
commit_subject=`get_commit_info "%s" "$original_head"`
commit_slug=`get_commit_info "%f" "$original_head"`
commit_body=`get_commit_body "$original_head"`
blog_title=`git config --get devblog.blog-title`

if [[ ${#commit_body} -gt 0 ]]; then
    commit_body_file="$commit_body"
    commit_body=`cat $commit_body_file`
    rm -rf "$commit_body_file"
    blog_article_template=`git config --get devblog.template-article|base64 -d|gunzip`
    blog_entry=`apply_shell_expansion "$blog_article_template"`
    echo "$blog_entry" > "${commit_slug}.html"
    git add "${commit_slug}.html"
    toc="<ul>"
    if ! is_initial_commit; then
        OLDIFS=$IFS
        IFS=$'\n'
        for previousline in `git log --pretty="format:%f %s"`; do
            prevfilename="${previousline%% *}.html"
            prevmessage="${previousline#* }"
            echo "prevfilename $prevfilename"
            echo "prevmessage $prevmessage"
            toc+="<li><a href=\"${prevfilename}\">$prevmessage</a></li>"
        done
        IFS="$OLDIFS"
    fi
    toc+="<li><a href=\"${commit_slug}.html\">$commit_subject</a></li>"
    toc+="</ul>"
    blog_index_template=`git config --get devblog.template-index|base64 -d|gunzip`
    index_entry=`apply_shell_expansion "$blog_index_template"`
    echo "$index_entry" > "index.html"
    git add "index.html"
    git commit -m "$commit_subject"
    if `git config --get devblog.auto-push`; then
        git push `git config --get devblog.blogging-remote` `git config --get devblog.blogging-branch`
    fi
fi

rm .git/devblog.lock
git checkout $original_branch
